spring:
  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.ws.server.MessageTracing.received: TRACE
      org.springframework.ws.client.MessageTracing: TRACE

soap:
  ws-location-uri: /crime-portal-gateway/ws/
  target-namespace: http://www.justice.gov.uk/magistrates/external/ExternalDocumentRequest
  keystore-password: changeit
  keystore-file-path: src/test/resources/keystore/server.jks
  xsd-file-path: src/main/resources/xsd/cp/external/ExternalDocumentRequest.xsd
