# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minReplicaCount: 1
maxReplicaCount: 2

image:
  repository: quay.io/hmpps/crime-portal-gateway
  tag: latest
  port: 8081

ingress:
  enabled: true
  enable_whitelist: true
  hosts:
    - host: crime-portal-gateway-dev.apps.live-1.cloud-platform.service.justice.gov.uk
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  SPRING_PROFILES_ACTIVE: "dev,logstash"
  INCLUDED_COURT_CODES: "B01BH,B01CE,B01CN,B01EF,B01GU,B01ND,B03DE,B10BD,B10JJ,B10JQ,B13HT,B14AV,B14ET,B14LO,B16BG,B16GB,B16HE,B17JA,B20BL,B20EB,B20EY,B20NP,B20OQ,B21DA,B21JI,B22GR,B22HM,B22KS,B22MZ,B23HS,B30PG,B31IT,B31JV,B32HX,B32UD,B33HU,B33II,B37HI,B40IM,B44BA,B47CL,B47OV,B54MW,B62DC,B62MV"

whitelist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
  bsi-1: "54.37.241.156/30"
  bsi-2: "167.71.136.237/32"
